### PR TITLE
feat: add support for palm release

### PR DESCRIPTION
**Pull request by mariajgrimaldi**
### Description
This PR adds support for the latest Open edX release. The Demo server already used this branch during the testing release effort for codejail deployment.

### CODE REVIEW

**Comment by mariajgrimaldi** [comment]
This will need a new release of: https://github.com/eduNEXT/codejailservice with tag 16.0.0 and a new image

**Comment by regisb** [comment]
:warning: You will need to bump the required tutor version in setup.py.

**Comment by MaferMazu** [comment]
@mariajgrimaldi, I will put this in the backlog to help you review this soon.
cc @santiagosuarezedunext

**Review by MaferMazu — APPROVED** [review]
I tested it, and as you said, we need the codejailservice in 16.0.0. I use the latest image and rename the tags, and it works.
I suggest we update the readme to add Palm in the compatibility notes and change quickstart to launch. But the rest looks good to me.

**Comment by dagg** [comment]
I also tried to use this and I get an error after running `tutor local launch` (I use the tutor version 16.0.2 and the palm.1 release of the Open edX)...

Installing it showed no errors though, only after trying to relaunch tutor, but maybe I did something wrong.

To install the palm version of the codejail plugin with the recent changes I run:
`$ pip install git+https://github.com/edunext/tutor-contrib-codejail@palm`

And then followed the rest of the instructions without errors until running `tutor local launch` and I got this:

```
⠿ codejailservice Error
Error response from daemon: manifest for ednxops/codejailservice:16.0.0 not found: manifest unknown: manifest unknown
```

I hope my feedback helps a bit.

**Comment by dagg** [comment]
> I also tried to use this and I get an error after running `tutor local launch` (I use the tutor version 16.0.2 and the palm.1 release of the Open edX)...
> 
> Installing it showed no errors though, only after trying to relaunch tutor, but maybe I did something wrong.
> 
> To install the palm version of the codejail plugin with the recent changes I run: `$ pip install git+https://github.com/edunext/tutor-contrib-codejail@palm`
> 
> And then followed the rest of the instructions without errors until running `tutor local launch` and I got this:
> 
> ```
> ⠿ codejailservice Error
> Error response from daemon: manifest for ednxops/codejailservice:16.0.0 not found: manifest unknown: manifest unknown
> ```
> 
> I hope my feedback helps a bit.

I managed to make it work and it seems to be ok now!

What I missed before and I found out thanks to @regisb was running the following for building the codejail images  after `tutor config save` and before `tutor local launch`  :

`tutor images build codejail`

After that everything seems to be working well!

It would be helpful if this part will also be included in the readme, as well as the `@palm` (or something that denotes the respective release) at the end of the repo link when running `pip install`. 

Thank you everyone!

**Comment by Asespinel** [comment]
@dagg Glad to hear you solved the issue. Nevertheless, I uploaded the 16.0.0 at the ednxops/codejailservice hub for further testings.

**Comment by Asespinel** [comment]
@mariajgrimaldi I tested this feature and everything is working as expected.

**Review by Asespinel — APPROVED** [review]

**Comment by mariajgrimaldi** [comment]
Is there any else we should do before merging?

**Pull request merged**
